[package]
authors = ["LongYinan <github@lyn.one>"]
edition = "2021"
name    = "oxc-node"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi         = { version = "3.0.0-alpha.4", default-features = false, features = ["async", "serde-json"] }
napi-derive  = { version = "3.0.0-alpha.3", default-features = false, features = ["type-def"] }
oxc          = { version = "0.16", features = ["codegen", "transformer"] }
oxc_resolver = "1"
phf          = "0.11"
serde        = { version = "1.0", features = ["derive"] }
tracing      = "0.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "fmt"] } # Omit the `regex` feature

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = "0.1"

[target.'cfg(all(target_os = "linux", not(target_arch = "arm")))'.dependencies]
mimalloc = { version = "0.1", features = ["local_dynamic_tls"] }

[build-dependencies]
napi-build = "2"

[profile.release]
codegen-units = 1
lto           = true
strip         = "symbols"
